### Exercise
Create a list containing the same elements as the list `[10, 20, 30, 40, 50, 60, 70]` using comprehensions

In [ ]:
### YOUR CODE HERE ###

### Example
Creating nested lists with comprehensions

In [ ]:
my_list = [[i for i in range(5)]]

In [ ]:
my_list

In [ ]:
type(my_list)

In [ ]:
type(my_list[0])

In [ ]:
my_list = [[i] for i in range(5)]

In [ ]:
my_list

In [ ]:
some_list = [1, 2, 3, 4]

In [ ]:
my_list = [[i] for i in some_list]

In [ ]:
my_list

In [ ]:
type(my_list)

In [ ]:
type(my_list[0])

In [ ]:
my_list = [[i, j] for i in range(2) for j in range(3)]

In [ ]:
my_list

In [ ]:
my_list = [[i for i in range(2)] for j in range(2)]

In [ ]:
my_list

In [ ]:
target_list = [[1, 2], [3, 4]]

In [ ]:
target_list

In [ ]:
my_list = [[i * 2 + j for j in range(1, 3)] for i in range(2)]

In [ ]:
my_list

### Exercise
Create the nested list `[[1, 2, 3], [4, 5, 6]]` using list comprehensions

In [ ]:
### YOUR CODE HERE ###

# Transforming lists

### Example
Transforming lists

In [ ]:
numbers = [1, 2, 3, 4, 5]
doubled_nums = []

In [ ]:
numbers

In [ ]:
doubled_nums

In [ ]:
for i in numbers:
    doubled_nums.append(i * 2)

In [ ]:
doubled_nums

It took multiple lines of code to achieve the task. Let's try with a comprehension.

In [ ]:
numbers

In [ ]:
double_nums = []
double_nums

In [ ]:
double_nums = [i * 2 for i in numbers]

In [ ]:
double_nums

In [ ]:
numbers

In [ ]:
squared_nums = [num ** 2 for num in numbers]

In [ ]:
squared_nums

### Exercise
Generate a new list by subtracting $1$ from each element of the original list `[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]` using comprehensions

In [ ]:
### YOUR CODE HERE ###

# Filtering elements from lists using comprehensions

### Example
List comprehensions with conditions

In [ ]:
even_list = [i for i in range(10) if i % 2 == 0]

In [ ]:
even_list

In [ ]:
odd_list = [i for i in range(10) if i % 2 != 0]

In [ ]:
odd_list

In [ ]:
words = ['apple', 'banana', 'kiwi', 'orange', 'grape']

In [ ]:
long_words = [word for word in words if len(word) > 5]

In [ ]:
long_words

In [ ]:
numbers = [-2, -1, 0, 1, 2, 3, 4, 5]

In [ ]:
pos_nums = [num for num in numbers if num > 0]

In [ ]:
pos_nums

### Exercise
Filter out the words from the list `['Adventure', 'Butterfly', 'Celebrate', 'Dreamland', 'Elephantine', 'Flashlight', 'Gravestone', 'Harmonious', 'Junglebook', 'Landscape']` whose lengths are odd numbers and print them

In [ ]:
### YOUR CODE HERE ###

### Exercise
Filter out the names from the list `['Sophia', 'Aarav', 'Olivia', 'Liam', 'Ananya', 'Neha', 'Emma', 'Rohan', 'Eesha', 'Noah', 'Arjun', 'Mia']` which start with vowels and print them

In [ ]:
### YOUR CODE HERE ###

# Set comprehensions

### Example
Set comprehensions

In [ ]:
my_set = {1, 2, 3, 4, 5}

In [ ]:
my_set

In [ ]:
comp_set = {num for num in my_set}

In [ ]:
comp_set

In [ ]:
comp_set = {num for num in range(6)}

In [ ]:
comp_set

In [ ]:
comp_set = {num for num in [23, 56, 76, 24, 52]}

In [ ]:
comp_set

In [ ]:
my_string = 'Some text'

In [ ]:
comp_set = {char for char in my_string}

In [ ]:
comp_set

### Exercise
Create a set comprehension containing unique elements from the following list `['world', 'b', 'hello', 'python', 42, 2.718, 7, 'world', 2.718, 'a', 'python', 42, 7, 7]`

In [ ]:
### YOUR CODE HERE ###

### Example
Creating nested sets with comprehensions

In [ ]:
# nested_comp_set = {{num for num in range(5)}}

In [ ]:
# nested_comp_set = set(set(y for y in range(5)) for x in range(2))

Recall that Python does not support directly nesting sets with in sets as sets by unhashable by themselves

# Transforming sets

### Example
Transforming sets

In [ ]:
my_set = {1, 2, 3, 4, 5, 6}

In [ ]:
quadrupled_set = {num * 4 for num in my_set}

In [ ]:
quadrupled_set

In [ ]:
my_set = {'basketball', 'football', 'cricket', 'curling', 'running'}

In [ ]:
capped_set = {word.upper() for word in my_set}

In [ ]:
capped_set

### Exercise
Given the set `{87, 12, 56, 34, 92, 5, 78, 43, 61, 20}`, create a new set that consists of half of each element from the original set.

In [ ]:
### YOUR CODE HERE ###

### Exercise
Given a set of ASCII values `{65, 66, 67, 68, 69, 70, 71, 72, 73, 74}` transform the set into another set containing their corresponding character encodings.

**Hint:** Do you recall the `chr` method?

In [ ]:
### YOUR CODE HERE ###

# Filtering elements from sets using comprehensions

### Example
Set comprehensions with conditions

In [ ]:
my_set = {1, 2, 3, 4, 5, 6}

In [ ]:
odd_set = {num for num in my_set if num % 2 != 0}

In [ ]:
odd_set

In [ ]:
even_set = {num for num in my_set if num % 2 == 0}

In [ ]:
even_set

In [ ]:
vegetables_set = {'carrot', 'broccoli', 'tomato', 'spinach', 'cucumber', 'bell pepper',
                  'zucchini', 'asparagus', 'sweet potato', 'cauliflower', 'kale',
                  'eggplant', 'green beans', 'peas', 'radish'}

fruits_set = {'apple', 'banana', 'orange', 'grape', 'kiwi', 'strawberry',
              'watermelon', 'pineapple', 'mango', 'peach', 'pear',
              'blueberry', 'raspberry', 'plum', 'cherry'}

In [ ]:
item_purch = {'carrot', 'broccoli', 'tomato', 'spinach', 'cucumber', 'bell pepper',
             'apple', 'banana', 'orange', 'grape', 'kiwi', 'strawberry'}

In [ ]:
fruit_purch = {item for item in item_purch if item in fruits_set}

In [ ]:
fruit_purch

In [ ]:
veggie_purch = {item for item in item_purch if item in vegetables_set}

In [ ]:
veggie_purch

### Exercise
Consider the following set of employee IDs:
```
{'QX42', 'YP78', 'AB91', 'LM29', 'JK53', 'DE87', 'VW16', 'FG49', 'MN72', 'OP83', 'HI59', 'RS20', 'CD34', 'TZ68', 'UV95'}
```
Extract those IDs which start with a consonant

In [ ]:
### YOUR CODE HERE ###

### Exercise
Consider the following set of employee IDs:
```
{'QX42', 'YP78', 'AB91', 'LM29', 'JK53', 'DE87', 'VW16', 'FG49', 'MN72', 'OP83', 'HI59', 'RS20', 'CD34', 'TZ68', 'UV95'}
```
Extract those IDs which end in an odd number

In [ ]:
### YOUR CODE HERE ###

### Exercise
Given a list of numbers `[3, 8, 15, 7, 11, 22, 5, 14]`, create a dictionary that maps the numbers with their cubes

In [ ]:
### YOUR CODE HERE ###

### Exercise
Create a dictionary that maps the characters in the list `['9', ')', '#', 'X', 'q', 'J', 'g', '+', '1', 'L']` with their respective ASCII values

In [ ]:
### YOUR CODE HERE ###

### Exercise
Consider the following list of car models: `['Toyota', 'Honda', 'Ford', 'Chevrolet', 'BMW', 'Mercedes', 'Tesla', 'Nissan']
`. Create a dictionary that maps the names of the cars with their first letter.

In [ ]:
### YOUR CODE HERE ###

### Example
Creating nested dictionaries with comprehensions

In [ ]:
users_data = {f'User {i + 1}': {'name': f'name {i + 1}'} for i in range(3)}

In [ ]:
users_data

In [ ]:
type(users_data)

In [ ]:
users_data['User 1']

In [ ]:
type(users_data['User 1'])

In [ ]:
user_data = {f'User {i + 1}': {'name': f'name {i + 1}', 'address': f'address {i + 1}'} for i in range(3)}

In [ ]:
user_data

In [ ]:
cities = ['Delhi', 'New York', 'Bangalore', 'Chenai', 'Mumbai']

In [ ]:
nested_dict = {word: {'first_let': word[0], 'length': len(word)} for word in cities}

In [ ]:
nested_dict

In [ ]:
user_ids = ['AB01', 'AB02', 'AB03', 'AB04', 'AB05']
user_names = ['alice123', 'bobSmith', 'charlie_22', 'davidSmith', 'emma_jones']
addresses = ['Delhi', 'New York', 'Bangalore', 'Chenai', 'Mumbai']

In [ ]:
users_data = {user_id: {'user_name': user_name, 'address': address} for user_id, user_name, address in zip(user_ids, user_names, addresses)}

In [ ]:
users_data

### Exercise
Consider the following list of car models: `['Toyota', 'Honda', 'Ford', 'Chevrolet', 'BMW', 'Mercedes', 'Tesla', 'Nissan']
`. Create a dictionary that maps the names of the cars with a dictionary that contains the characters in the names of the cars along with their frequency of occurence in the names. Treat lower and upper case characters differently.

**Hint:** Do you recall the `count` method?

In [ ]:
### YOUR CODE HERE ###

### Exercise
Consider the following list of car models: `['Toyota', 'Honda', 'Ford', 'Chevrolet', 'BMW', 'Mercedes', 'Tesla', 'Nissan']
`. Create a dictionary that maps the names of the cars with a dictionary that contains the characters in the names of the cars along with their frequency of occurence in the names. Treat lower and upper case characters as the same.

In [ ]:
### YOUR CODE HERE ###

# Transforming dictionaries

### Example
Transforming dictionaries

In [ ]:
original_dict = {'a': 2, 'b': 3, 'c': 4}
original_dict

In [ ]:
squared_dict = {key: value ** 2 for key, value in original_dict.items()}

In [ ]:
squared_dict

In [ ]:
rev_key_value = {value: key for key, value in original_dict.items()}

In [ ]:
rev_key_value

### Exercise
Consider the following dictionary of student names and their exam scores:
`{'Alice': 85, 'Bob': 60, 'Charlie': 75, 'David': 95}`

It has come to the attention of the management committee that one of the questions was incorrect and was worth $3$ marks. Rectify the dictionary.

In [ ]:
### YOUR CODE HERE ###

# Filtering elements from dicitionaries using comprehensions

### Example
Dictionary comprehensions with conditions

In [ ]:
my_dict = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

In [ ]:
even_dict = {key: value for key, value in my_dict.items() if value % 2 == 0}

In [ ]:
even_dict

In [ ]:
even_dict = {key: 'even' if value % 2 == 0 else 'odd' for key, value in my_dict.items()}

In [ ]:
even_dict

In [ ]:
odd_dict = {key: value for key, value in my_dict.items() if value % 2 != 0}

In [ ]:
odd_dict

In [ ]:
temperature_readings = [28.5, 28.7, 29.0, 29.5, 30.2, 30.9, 31.2, 31.8, 32.0, 33.5]

In [ ]:
temp_map_dict = {temp: 'Hot' if temp > 30 else 'Mild' for temp in temperature_readings}

In [ ]:
temp_map_dict

In [ ]:
fruits_set

In [ ]:
vegetables_set

In [ ]:
item_purch

In [ ]:
map_dict = {item: 'Vegetable' if item in vegetables_set else 'Fruit' for item in item_purch}

In [ ]:
map_dict

### Exercise
Consider the following employee compensations:
```
emp_details = {'Anand': 196542, 'Chitra': 209065, 'David': 155687, 'Ehsaan': 344762, 'Fatima': 278564, 'Gokul': 400142}
```
Create a new dictionary that shows the employee names against dictionaries that contain compensation values and whether the employee is taxable or not. Use `'Compensation'` as the key for the compensation values and `'Taxable'` as the key for whether the employee is taxable or not, with possible values as `'Yes'` or `'No'`. Assume that any compensation below $300000$ is not taxable.

In [ ]:
### YOUR CODE HERE ###

### Exercise
Given a set of possible prouct ratings `{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}`, create a dictionary the maps the numbers based on the following conditions:
- If the rating is smaller than 5, then call it `'low'`
- If the rating lies between 5 and 8, both inclusive, then call it `'medium'`
- If the rating is greater than 8, then call it `'high'`

In [ ]:
### YOUR CODE HERE ###

### Exercise
Given a list of numbers `[1, 5, 10, 20, 25, 30, 42, 55, 67, 80]`, find their sum using a built-in function

In [ ]:
### YOUR CODE HERE ###

### Exercise
Write a function named `say_hello` that prints a greeting message

In [ ]:
### YOUR CODE HERE ###

In [ ]:
### YOUR CODE HERE ###

### Exercise
Create a function that accepts the name of the user and returns the length of their name

In [ ]:
### YOUR CODE HERE ###

In [ ]:
### YOUR CODE HERE ###

### Example
**Parameters** are variables listed in the function definition. They are placeholders for values that a function will receive when it is called.

**Arguments** are the actual values or expressions that are passed to a function when it is called.

In [ ]:
def diff(num_1, num_2): # Here num_1 and num_2 are parameters (placeholders)
    return num_1 - num_2

In [ ]:
diff_res = diff(10, -10) # Here 10 and -10 are arguments (actual values)
diff_res

### Exercise
Write a function that calculates the area of a rectangle by taking a length and width. Assume the default width to be `5` units.

In [ ]:
### YOUR CODE HERE ###

In [ ]:
### YOUR CODE HERE ###

In [ ]:
### YOUR CODE HERE ###

In [ ]:
### YOUR CODE HERE ###

In [ ]:
### YOUR CODE HERE ###

### Exercise
Write a function that takes a list of prices of items purchased and calculates the total cost. Assume the tax rate as `tax_rate = 0.1` and discount as `discount = 0`. The total cost is given by `total cost = subtotal * (1 + tax_rate) - discount`.

In [ ]:
### YOUR CODE HERE ###

In [ ]:
### YOUR CODE HERE ###

### Example
Passing tuples as arguments

In [ ]:
def transform_point(my_point, constant = 2):
    transformed = [cor_val * 2 for cor_val in my_point]
    return transformed

In [ ]:
transform_point((1, -1, 1))

### Exercise
Create a function that takes two tuple containing the `x` and `y` coordinate values of two points and computes the Euclidean distance

In [ ]:
### YOUR CODE HERE ###

In [ ]:
### YOUR CODE HERE ###

In [ ]:
### YOUR CODE HERE ###

### Example
Passing sets as arguments

In [ ]:
def extract_unique(my_set): return my_set

In [ ]:
extract_unique({5, 2, 8, 1, 3, 1, 5, 2})

In [ ]:
def find_common(set1, set2):
    common_elements = set1.intersection(set2)
    return common_elements

In [ ]:
set_a = {1, 2, 3, 4, 5}
set_b = {3, 4, 5, 6, 7}

In [ ]:
result = find_common(set_a, set_b)
result

### Exercise
Create a function that accepts two sets and return the symmetric different of the two sets

In [ ]:
### YOUR CODE HERE ###

In [ ]:
### YOUR CODE HERE ###

In [ ]:
### YOUR CODE HERE ###

### Exercise
Create a lambda function that takes a list return the number of elements in a list

In [ ]:
### YOUR CODE HERE ###

In [ ]:
### YOUR CODE HERE ###

In [ ]:
### YOUR CODE HERE ###

### Exercise
Use the `map()` function to create a new list wherein each element corresponds to the uppercase version of the respective word in the input list

In [ ]:
### YOUR CODE HERE ###

In [ ]:
### YOUR CODE HERE ###

In [ ]:
### YOUR CODE HERE ###

### Exercise
Use `map` to generate a list that transforms an input list of numeric strings into strings. Use `["1", "2", "3", "4", "5"]` as your input.

In [ ]:
### YOUR CODE HERE ###

In [ ]:
### YOUR CODE HERE ###

In [ ]:
### YOUR CODE HERE ###